# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userzy',
            fields=[
                ('nr', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
    ]
